apiVersion: v1
kind: Secret
stringData:
  access_key_id: <access_key_id>
  access_key_secret: <access_key_secret>
  bucket: <bucket_name>
  endpoint: 'https://s3.us-east-1.amazonaws.com'
  region: 'us-east-1'
metadata:
  name: coo-tracing-tempo
  namespace: observability
type: Opaque
